### ISSUE TITLE
Install fails: docwhat.org/go-git-info not found

### ISSUE THREAD

**Issue by dritter** [docwhat/go-git-info#2]
Hi Chris,

the install of this package fails with the message:
```
can't load package: package docwhat.org/go-git-info: unknown import path "docwhat.org/go-git-info": cannot find module providing package docwhat.org/go-git-info
```

This happens on `go build` and `go install`. Am I doing something wrong?

**Comment by docwhat** [comment]
Fixed by #3 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
